"""initial migration

Revision ID: 16646b0608dd
Revises: 
Create Date: 2025-07-24 14:36:20.874913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16646b0608dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(length=64), nullable=True),
    sa.Column('cost_items', sa.JSON(), nullable=True),
    sa.Column('cost_details', sa.JSON(), nullable=True),
    sa.Column('unit_cost_label', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_type')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('project_type', sa.String(length=64), nullable=True),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)

    op.create_table('profit_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('total_project_cost', sa.Float(), nullable=True),
    sa.Column('market_profit_rate', sa.Float(), nullable=True),
    sa.Column('extra_investment', sa.Float(), nullable=True),
    sa.Column('resource_fee_total', sa.Float(), nullable=True),
    sa.Column('commission_income', sa.Float(), nullable=True),
    sa.Column('resource_income', sa.Float(), nullable=True),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profit_analysis')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))

    op.drop_table('project')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('cost_model')
    # ### end Alembic commands ###
