"""Add ProjectCostDetail model for custom project cost items

Revision ID: 96c7cb994d99
Revises: c723d3c04838
Create Date: 2025-07-24 17:10:52.427577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c7cb994d99'
down_revision = 'c723d3c04838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_cost_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cost_category', sa.String(length=64), nullable=False),
    sa.Column('cost_item', sa.String(length=128), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('unit_label', sa.String(length=20), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_cost_detail')
    # ### end Alembic commands ###
