"""Add new fields to ProfitAnalysis model according to technical documentation V2.0

Revision ID: c723d3c04838
Revises: 16646b0608dd
Create Date: 2025-07-24 16:45:50.025425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c723d3c04838'
down_revision = '16646b0608dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('profit_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_fee_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dengpin_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('net_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('roi_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profit_analysis', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('roi_percentage')
        batch_op.drop_column('net_profit')
        batch_op.drop_column('dengpin_cost')
        batch_op.drop_column('dev_fee_rate')

    with op.batch_alter_table('cost_model', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
